use("learnhub");

db.users.drop();
db.courses.drop();
db.lessons.drop();
db.enrollments.drop();
db.reviews.drop();

// ══════════════════════════════════════════════
// USERS — 20 documents
// ══════════════════════════════════════════════
db.users.insertMany([
  { firstName: "Bob",      lastName: "Dupont",   email: "bob.dupont@email.com",      role: "instructor", profile: { bio: "Expert MongoDB",           avatar: "https://i.pravatar.cc/150?img=2",  city: "Lyon",        country: "France" }, skills: ["MongoDB","Node.js","Express"],          isActive: true,  totalCoursesEnrolled: 0, createdAt: new Date("2023-06-10"), lastLoginAt: new Date("2024-11-20") },
  { firstName: "David",    lastName: "Morel",    email: "david.morel@email.com",     role: "instructor", profile: { bio: "Spécialiste DevOps",        avatar: "https://i.pravatar.cc/150?img=4",  city: "Bordeaux",    country: "France" }, skills: ["Docker","Kubernetes","AWS"],            isActive: true,  totalCoursesEnrolled: 0, createdAt: new Date("2023-03-01"), lastLoginAt: new Date("2024-12-05") },
  { firstName: "Hugo",     lastName: "Simon",    email: "hugo.simon@email.com",      role: "instructor", profile: { bio: "Dev Mobile Senior",        avatar: "https://i.pravatar.cc/150?img=8",  city: "Nice",        country: "France" }, skills: ["React Native","Flutter","Swift"],       isActive: true,  totalCoursesEnrolled: 0, createdAt: new Date("2023-09-15"), lastLoginAt: new Date("2024-12-08") },
  { firstName: "Lucas",    lastName: "Thomas",   email: "lucas.thomas@email.com",    role: "instructor", profile: { bio: "Expert IA et ML",          avatar: "https://i.pravatar.cc/150?img=12", city: "Paris",       country: "France" }, skills: ["Python","PyTorch","Scikit-learn"],      isActive: true,  totalCoursesEnrolled: 0, createdAt: new Date("2023-01-20"), lastLoginAt: new Date("2024-12-07") },
  { firstName: "Pierre",   lastName: "Fontaine", email: "pierre.fontaine@email.com", role: "instructor", profile: { bio: "Architecte Full Stack",     avatar: "https://i.pravatar.cc/150?img=16", city: "Paris",       country: "France" }, skills: ["React","Node.js","AWS","TypeScript"],   isActive: true,  totalCoursesEnrolled: 0, createdAt: new Date("2022-11-05"), lastLoginAt: new Date("2024-12-03") },
  { firstName: "Alice",    lastName: "Martin",   email: "alice.martin@email.com",    role: "student",    profile: { bio: "Étudiante en informatique", avatar: "https://i.pravatar.cc/150?img=1",  city: "Paris",       country: "France" }, skills: ["JavaScript","Python"],                  isActive: true,  totalCoursesEnrolled: 3, createdAt: new Date("2024-01-15"), lastLoginAt: new Date("2024-12-01") },
  { firstName: "Clara",    lastName: "Lefebvre", email: "clara.lefebvre@email.com",  role: "student",    profile: { bio: "Dev Web Junior",           avatar: "https://i.pravatar.cc/150?img=3",  city: "Paris",       country: "France" }, skills: ["HTML","CSS","JavaScript"],              isActive: true,  totalCoursesEnrolled: 2, createdAt: new Date("2024-02-20"), lastLoginAt: new Date("2024-10-15") },
  { firstName: "Emma",     lastName: "Bernard",  email: "emma.bernard@email.com",    role: "student",    profile: { bio: "Passionnée d'IA",          avatar: "https://i.pravatar.cc/150?img=5",  city: "Marseille",   country: "France" }, skills: ["Python","TensorFlow"],                  isActive: false, totalCoursesEnrolled: 1, createdAt: new Date("2024-03-10"), lastLoginAt: new Date("2024-05-01") },
  { firstName: "Félix",    lastName: "Garnier",  email: "felix.garnier@email.com",   role: "student",    profile: { bio: "Étudiant cybersécurité",    avatar: "https://i.pravatar.cc/150?img=6",  city: "Toulouse",    country: "France" }, skills: ["Linux","Python","Bash"],                isActive: true,  totalCoursesEnrolled: 4, createdAt: new Date("2024-01-05"), lastLoginAt: new Date("2024-12-10") },
  { firstName: "Gaelle",   lastName: "Petit",    email: "gaelle.petit@email.com",    role: "student",    profile: { bio: "Designer UX/UI",           avatar: "https://i.pravatar.cc/150?img=7",  city: "Paris",       country: "France" }, skills: ["Figma","CSS","React"],                  isActive: true,  totalCoursesEnrolled: 2, createdAt: new Date("2024-04-18"), lastLoginAt: new Date("2024-11-30") },
  { firstName: "Isabelle", lastName: "Laurent",  email: "isabelle.laurent@email.com",role: "student",    profile: { bio: "Reconversion vers le dev",  avatar: "https://i.pravatar.cc/150?img=9",  city: "Nantes",      country: "France" }, skills: ["JavaScript","React"],                   isActive: true,  totalCoursesEnrolled: 3, createdAt: new Date("2024-05-22"), lastLoginAt: new Date("2024-12-02") },
  { firstName: "Julien",   lastName: "Roux",     email: "julien.roux@email.com",     role: "student",    profile: { bio: "Backend developer Java",    avatar: "https://i.pravatar.cc/150?img=10", city: "Strasbourg",  country: "France" }, skills: ["Java","Spring","SQL"],                  isActive: false, totalCoursesEnrolled: 1, createdAt: new Date("2023-11-10"), lastLoginAt: new Date("2024-04-20") },
  { firstName: "Karen",    lastName: "Michel",   email: "karen.michel@email.com",    role: "student",    profile: { bio: "Data Analyst",             avatar: "https://i.pravatar.cc/150?img=11", city: "Paris",       country: "France" }, skills: ["Python","Pandas","SQL"],                isActive: true,  totalCoursesEnrolled: 5, createdAt: new Date("2024-02-01"), lastLoginAt: new Date("2024-12-09") },
  { firstName: "Marie",    lastName: "Blanc",    email: "marie.blanc@email.com",     role: "student",    profile: { bio: "Freelance dev web",         avatar: "https://i.pravatar.cc/150?img=13", city: "Lille",       country: "France" }, skills: ["Vue.js","Node.js","MongoDB"],           isActive: true,  totalCoursesEnrolled: 2, createdAt: new Date("2024-06-15"), lastLoginAt: new Date("2024-11-25") },
  { firstName: "Nicolas",  lastName: "Renard",   email: "nicolas.renard@email.com",  role: "student",    profile: { bio: "Étudiant en L3 info",       avatar: "https://i.pravatar.cc/150?img=14", city: "Rennes",      country: "France" }, skills: ["C++","Python"],                         isActive: true,  totalCoursesEnrolled: 1, createdAt: new Date("2024-09-01"), lastLoginAt: new Date("2024-12-11") },
  { firstName: "Olivia",   lastName: "Durand",   email: "olivia.durand@email.com",   role: "student",    profile: { bio: "Ingénieure logiciel Go",    avatar: "https://i.pravatar.cc/150?img=15", city: "Paris",       country: "France" }, skills: ["Go","Kubernetes","PostgreSQL"],          isActive: false, totalCoursesEnrolled: 2, createdAt: new Date("2023-07-30"), lastLoginAt: new Date("2024-03-15") },
  { firstName: "Quentin",  lastName: "Leclerc",  email: "quentin.leclerc@email.com", role: "student",    profile: { bio: "Passionné NoSQL",           avatar: "https://i.pravatar.cc/150?img=17", city: "Grenoble",    country: "France" }, skills: ["MongoDB","Redis","Cassandra"],           isActive: true,  totalCoursesEnrolled: 3, createdAt: new Date("2024-01-28"), lastLoginAt: new Date("2024-12-12") },
  { firstName: "Rachel",   lastName: "Moreau",   email: "rachel.moreau@email.com",   role: "student",    profile: { bio: "Chef de projet tech",       avatar: "https://i.pravatar.cc/150?img=18", city: "Lyon",        country: "France" }, skills: ["Agile","Scrum","Jira"],                 isActive: true,  totalCoursesEnrolled: 2, createdAt: new Date("2024-03-20"), lastLoginAt: new Date("2024-11-18") },
  { firstName: "Samuel",   lastName: "Vincent",  email: "samuel.vincent@email.com",  role: "student",    profile: { bio: "Junior dev full stack",     avatar: "https://i.pravatar.cc/150?img=19", city: "Montpellier", country: "France" }, skills: ["JavaScript","Node.js","React"],         isActive: true,  totalCoursesEnrolled: 4, createdAt: new Date("2024-02-14"), lastLoginAt: new Date("2024-12-06") },
  { firstName: "Tina",     lastName: "Robert",   email: "tina.robert@email.com",     role: "student",    profile: { bio: "Dev WordPress/PHP",         avatar: "https://i.pravatar.cc/150?img=20", city: "Paris",       country: "France" }, skills: ["HTML","CSS","WordPress","PHP"],          isActive: true,  totalCoursesEnrolled: 1, createdAt: new Date("2024-07-01"), lastLoginAt: new Date("2024-10-30") }
]);

print("✅ Users : " + db.users.countDocuments());

const bob    = db.users.findOne({ email: "bob.dupont@email.com"      });
const david  = db.users.findOne({ email: "david.morel@email.com"     });
const hugo   = db.users.findOne({ email: "hugo.simon@email.com"      });
const lucas  = db.users.findOne({ email: "lucas.thomas@email.com"    });
const pierre = db.users.findOne({ email: "pierre.fontaine@email.com" });

// ══════════════════════════════════════════════
// COURSES — 15 documents
// ══════════════════════════════════════════════
db.courses.insertMany([
  { title: "MongoDB pour Débutants",             description: "Apprenez les bases de MongoDB, collections, documents, CRUD et agrégations.",           instructorId: bob._id,    category: "Database", difficulty: "beginner",     price: 49.99, tags: ["mongodb","nosql","database"],               metadata: { duration: 1200, totalLessons: 12, language: "fr" }, rating: { average: 4.5, count: 28  }, isPublished: true,  enrollmentCount: 156, createdAt: new Date("2024-03-01"), updatedAt: new Date("2024-11-20") },
  { title: "React.js Avancé",                    description: "Maîtrisez les hooks avancés, le contexte API et les performances React.",               instructorId: pierre._id, category: "Web",      difficulty: "advanced",     price: 89.99, tags: ["react","javascript","frontend"],            metadata: { duration: 1800, totalLessons: 20, language: "fr" }, rating: { average: 4.8, count: 65  }, isPublished: true,  enrollmentCount: 312, createdAt: new Date("2024-01-10"), updatedAt: new Date("2024-12-01") },
  { title: "Docker & Kubernetes",                description: "Déployez et orchestrez vos applications avec Docker et Kubernetes.",                    instructorId: david._id,  category: "DevOps",   difficulty: "intermediate", price: 69.99, tags: ["docker","kubernetes","devops"],             metadata: { duration: 1500, totalLessons: 15, language: "fr" }, rating: { average: 4.6, count: 42  }, isPublished: true,  enrollmentCount: 198, createdAt: new Date("2024-02-15"), updatedAt: new Date("2024-11-10") },
  { title: "Machine Learning avec Python",       description: "Introduction au ML : régression, classification et clustering avec Scikit-learn.",       instructorId: lucas._id,  category: "AI",       difficulty: "intermediate", price: 79.99, tags: ["python","ml","ai","scikit-learn"],          metadata: { duration: 2400, totalLessons: 25, language: "fr" }, rating: { average: 4.7, count: 89  }, isPublished: true,  enrollmentCount: 445, createdAt: new Date("2023-11-01"), updatedAt: new Date("2024-12-05") },
  { title: "React Native — Applications Mobiles",description: "Créez des applications iOS et Android avec React Native et Expo.",                       instructorId: hugo._id,   category: "Mobile",   difficulty: "intermediate", price: 59.99, tags: ["react-native","mobile","ios","android"],    metadata: { duration: 1600, totalLessons: 18, language: "fr" }, rating: { average: 4.3, count: 31  }, isPublished: true,  enrollmentCount: 167, createdAt: new Date("2024-04-01"), updatedAt: new Date("2024-11-28") },
  { title: "Node.js & Express — API REST",       description: "Construisez des API REST robustes et sécurisées avec Node.js et Express.",               instructorId: pierre._id, category: "Web",      difficulty: "beginner",     price: 44.99, tags: ["nodejs","express","api","backend"],         metadata: { duration: 1000, totalLessons: 10, language: "fr" }, rating: { average: 4.4, count: 52  }, isPublished: true,  enrollmentCount: 289, createdAt: new Date("2024-02-01"), updatedAt: new Date("2024-10-15") },
  { title: "PostgreSQL Avancé",                  description: "Optimisez vos requêtes SQL, index, triggers et fonctions PostgreSQL.",                   instructorId: bob._id,    category: "Database", difficulty: "advanced",     price: 74.99, tags: ["postgresql","sql","database"],              metadata: { duration: 1400, totalLessons: 14, language: "fr" }, rating: { average: 4.2, count: 19  }, isPublished: true,  enrollmentCount: 98,  createdAt: new Date("2024-05-10"), updatedAt: new Date("2024-11-05") },
  { title: "Flutter — Dev Multiplateforme",      description: "Créez des applications multiplateforme avec Flutter et Dart.",                           instructorId: hugo._id,   category: "Mobile",   difficulty: "beginner",     price: 39.99, tags: ["flutter","dart","mobile"],                  metadata: { duration: 1100, totalLessons: 11, language: "fr" }, rating: { average: 4.1, count: 24  }, isPublished: false, enrollmentCount: 45,  createdAt: new Date("2024-07-20"), updatedAt: new Date("2024-09-01") },
  { title: "CI/CD avec GitHub Actions",          description: "Automatisez vos pipelines de déploiement avec GitHub Actions.",                         instructorId: david._id,  category: "DevOps",   difficulty: "beginner",     price: 29.99, tags: ["github-actions","cicd","devops"],           metadata: { duration: 600,  totalLessons: 8,  language: "fr" }, rating: { average: 4.5, count: 37  }, isPublished: true,  enrollmentCount: 220, createdAt: new Date("2024-06-01"), updatedAt: new Date("2024-11-15") },
  { title: "Deep Learning & Réseaux de Neurones",description: "Plongez dans le Deep Learning avec PyTorch, CNN et Transfer Learning.",                  instructorId: lucas._id,  category: "AI",       difficulty: "advanced",     price: 99.99, tags: ["deep-learning","pytorch","cnn","ai"],       metadata: { duration: 3000, totalLessons: 30, language: "fr" }, rating: { average: 4.9, count: 112 }, isPublished: true,  enrollmentCount: 567, createdAt: new Date("2023-08-15"), updatedAt: new Date("2024-12-10") },
  { title: "Vue.js 3 — Composition API",         description: "Maîtrisez Vue.js 3, la Composition API, Pinia et Vue Router.",                          instructorId: pierre._id, category: "Web",      difficulty: "intermediate", price: 54.99, tags: ["vuejs","javascript","frontend","pinia"],    metadata: { duration: 1300, totalLessons: 14, language: "fr" }, rating: { average: 4.6, count: 44  }, isPublished: true,  enrollmentCount: 234, createdAt: new Date("2024-03-20"), updatedAt: new Date("2024-11-22") },
  { title: "Redis — Cache et Messaging",         description: "Utilisez Redis comme cache haute performance et broker de messages.",                    instructorId: bob._id,    category: "Database", difficulty: "intermediate", price: 34.99, tags: ["redis","cache","nosql","messaging"],        metadata: { duration: 800,  totalLessons: 9,  language: "fr" }, rating: { average: 4.0, count: 15  }, isPublished: true,  enrollmentCount: 78,  createdAt: new Date("2024-08-01"), updatedAt: new Date("2024-10-20") },
  { title: "AWS pour Développeurs",              description: "Déployez vos applications sur AWS : EC2, S3, Lambda et RDS.",                           instructorId: david._id,  category: "DevOps",   difficulty: "intermediate", price: 84.99, tags: ["aws","cloud","devops","serverless"],        metadata: { duration: 2000, totalLessons: 22, language: "fr" }, rating: { average: 4.4, count: 58  }, isPublished: true,  enrollmentCount: 301, createdAt: new Date("2024-01-25"), updatedAt: new Date("2024-12-08") },
  { title: "JavaScript Moderne — ES2024",        description: "Maîtrisez les dernières fonctionnalités JS : async/await, modules, destructuring.",     instructorId: pierre._id, category: "Web",      difficulty: "beginner",     price: 19.99, tags: ["javascript","es6","web"],                   metadata: { duration: 900,  totalLessons: 10, language: "fr" }, rating: { average: 4.3, count: 76  }, isPublished: true,  enrollmentCount: 412, createdAt: new Date("2024-04-10"), updatedAt: new Date("2024-11-30") },
  { title: "NLP — Traitement du Langage Naturel",description: "Introduction au NLP avec Python, spaCy et les modèles Transformers.",                    instructorId: lucas._id,  category: "AI",       difficulty: "advanced",     price: 94.99, tags: ["nlp","python","transformers","ai"],         metadata: { duration: 2600, totalLessons: 26, language: "fr" }, rating: { average: 4.8, count: 67  }, isPublished: true,  enrollmentCount: 389, createdAt: new Date("2024-02-28"), updatedAt: new Date("2024-12-03") }
]);

print("✅ Courses : " + db.courses.countDocuments());

const mongoCourse  = db.courses.findOne({ title: "MongoDB pour Débutants"                });
const reactCourse  = db.courses.findOne({ title: "React.js Avancé"                       });
const dockerCourse = db.courses.findOne({ title: "Docker & Kubernetes"                   });
const mlCourse     = db.courses.findOne({ title: "Machine Learning avec Python"          });
const rnCourse     = db.courses.findOne({ title: "React Native — Applications Mobiles"   });
const nodeCourse   = db.courses.findOne({ title: "Node.js & Express — API REST"          });
const pgCourse     = db.courses.findOne({ title: "PostgreSQL Avancé"                     });
const flutterCourse= db.courses.findOne({ title: "Flutter — Dev Multiplateforme"         });
const cicdCourse   = db.courses.findOne({ title: "CI/CD avec GitHub Actions"             });
const dlCourse     = db.courses.findOne({ title: "Deep Learning & Réseaux de Neurones"   });
const vueCourse    = db.courses.findOne({ title: "Vue.js 3 — Composition API"            });
const redisCourse  = db.courses.findOne({ title: "Redis — Cache et Messaging"            });
const awsCourse    = db.courses.findOne({ title: "AWS pour Développeurs"                 });
const jsCourse     = db.courses.findOne({ title: "JavaScript Moderne — ES2024"           });
const nlpCourse    = db.courses.findOne({ title: "NLP — Traitement du Langage Naturel"   });

// ══════════════════════════════════════════════
// LESSONS — 30 documents (2 par cours)
// ══════════════════════════════════════════════
db.lessons.insertMany([
  { courseId: mongoCourse._id,   title: "Introduction à MongoDB",              content: "Découverte de MongoDB et des bases NoSQL.",              type: "video", order: 1, duration: 30, resources: [{ name: "Slides", url: "https://learnhub.com/r/mongo-l1.pdf"    }], isFree: true,  createdAt: new Date("2024-03-01") },
  { courseId: mongoCourse._id,   title: "CRUD et Requêtes de base",            content: "Insérer, lire, modifier et supprimer des documents.",    type: "text",  order: 2, duration: 45, resources: [{ name: "Exercices", url: "https://learnhub.com/r/mongo-l2.pdf" }], isFree: false, createdAt: new Date("2024-03-01") },
  { courseId: reactCourse._id,   title: "Introduction à React",                content: "Composants, JSX et props.",                              type: "video", order: 1, duration: 35, resources: [{ name: "Slides", url: "https://learnhub.com/r/react-l1.pdf"    }], isFree: true,  createdAt: new Date("2024-01-10") },
  { courseId: reactCourse._id,   title: "Hooks avancés",                       content: "useCallback, useMemo et hooks personnalisés.",            type: "video", order: 2, duration: 60, resources: [{ name: "Code",   url: "https://learnhub.com/r/react-l2.zip"   }], isFree: false, createdAt: new Date("2024-01-10") },
  { courseId: dockerCourse._id,  title: "Introduction à Docker",               content: "Conteneurs, images et Dockerfile.",                      type: "video", order: 1, duration: 40, resources: [{ name: "Slides", url: "https://learnhub.com/r/docker-l1.pdf"   }], isFree: true,  createdAt: new Date("2024-02-15") },
  { courseId: dockerCourse._id,  title: "Docker Compose et orchestration",     content: "Déployer des stacks multi-conteneurs.",                   type: "text",  order: 2, duration: 50, resources: [{ name: "Code",   url: "https://learnhub.com/r/docker-l2.zip"  }], isFree: false, createdAt: new Date("2024-02-15") },
  { courseId: mlCourse._id,      title: "Introduction au Machine Learning",    content: "Concepts fondamentaux du ML supervisé.",                  type: "video", order: 1, duration: 45, resources: [{ name: "Slides", url: "https://learnhub.com/r/ml-l1.pdf"      }], isFree: true,  createdAt: new Date("2023-11-01") },
  { courseId: mlCourse._id,      title: "Régression et Classification",        content: "Algorithmes de régression linéaire et logistique.",       type: "video", order: 2, duration: 60, resources: [{ name: "Notebook", url: "https://learnhub.com/r/ml-l2.ipynb"  }], isFree: false, createdAt: new Date("2023-11-01") },
  { courseId: rnCourse._id,      title: "Introduction à React Native",         content: "Setup Expo et premier composant mobile.",                 type: "video", order: 1, duration: 35, resources: [{ name: "Slides", url: "https://learnhub.com/r/rn-l1.pdf"      }], isFree: true,  createdAt: new Date("2024-04-01") },
  { courseId: rnCourse._id,      title: "Navigation et Composants natifs",     content: "React Navigation et composants iOS/Android.",             type: "text",  order: 2, duration: 50, resources: [{ name: "Code",   url: "https://learnhub.com/r/rn-l2.zip"     }], isFree: false, createdAt: new Date("2024-04-01") },
  { courseId: nodeCourse._id,    title: "Introduction à Node.js",              content: "Event loop, modules et npm.",                            type: "video", order: 1, duration: 30, resources: [{ name: "Slides", url: "https://learnhub.com/r/node-l1.pdf"    }], isFree: true,  createdAt: new Date("2024-02-01") },
  { courseId: nodeCourse._id,    title: "API REST avec Express",               content: "Routing, middlewares et gestion des erreurs.",            type: "video", order: 2, duration: 45, resources: [{ name: "Code",   url: "https://learnhub.com/r/node-l2.zip"   }], isFree: false, createdAt: new Date("2024-02-01") },
  { courseId: pgCourse._id,      title: "Introduction à PostgreSQL",           content: "Bases de SQL et modélisation relationnelle.",             type: "video", order: 1, duration: 40, resources: [{ name: "Slides", url: "https://learnhub.com/r/pg-l1.pdf"     }], isFree: true,  createdAt: new Date("2024-05-10") },
  { courseId: pgCourse._id,      title: "Index et optimisation",               content: "Types d'index, EXPLAIN et optimisation des requêtes.",    type: "text",  order: 2, duration: 55, resources: [{ name: "Exercices", url: "https://learnhub.com/r/pg-l2.pdf" }], isFree: false, createdAt: new Date("2024-05-10") },
  { courseId: flutterCourse._id, title: "Introduction à Flutter",              content: "Setup et premier widget Flutter.",                        type: "video", order: 1, duration: 35, resources: [{ name: "Slides", url: "https://learnhub.com/r/flutter-l1.pdf" }], isFree: true,  createdAt: new Date("2024-07-20") },
  { courseId: flutterCourse._id, title: "Widgets et State Management",         content: "StatefulWidget, Provider et Riverpod.",                   type: "video", order: 2, duration: 50, resources: [{ name: "Code",   url: "https://learnhub.com/r/flutter-l2.zip"}], isFree: false, createdAt: new Date("2024-07-20") },
  { courseId: cicdCourse._id,    title: "Introduction à GitHub Actions",       content: "Workflows, jobs et steps.",                              type: "video", order: 1, duration: 30, resources: [{ name: "Slides", url: "https://learnhub.com/r/cicd-l1.pdf"    }], isFree: true,  createdAt: new Date("2024-06-01") },
  { courseId: cicdCourse._id,    title: "Pipeline de déploiement complet",     content: "Build, tests automatisés et déploiement continu.",        type: "text",  order: 2, duration: 45, resources: [{ name: "Code",   url: "https://learnhub.com/r/cicd-l2.zip"   }], isFree: false, createdAt: new Date("2024-06-01") },
  { courseId: dlCourse._id,      title: "Introduction au Deep Learning",       content: "Perceptrons, activation et backpropagation.",             type: "video", order: 1, duration: 50, resources: [{ name: "Slides", url: "https://learnhub.com/r/dl-l1.pdf"     }], isFree: true,  createdAt: new Date("2023-08-15") },
  { courseId: dlCourse._id,      title: "Réseaux de neurones convolutifs",     content: "Architecture CNN et Transfer Learning.",                  type: "video", order: 2, duration: 70, resources: [{ name: "Notebook", url: "https://learnhub.com/r/dl-l2.ipynb" }], isFree: false, createdAt: new Date("2023-08-15") },
  { courseId: vueCourse._id,     title: "Introduction à Vue.js 3",             content: "Composition API, ref et reactive.",                       type: "video", order: 1, duration: 35, resources: [{ name: "Slides", url: "https://learnhub.com/r/vue-l1.pdf"     }], isFree: true,  createdAt: new Date("2024-03-20") },
  { courseId: vueCourse._id,     title: "Pinia et Vue Router",                 content: "Gestion d'état avec Pinia et navigation.",                type: "text",  order: 2, duration: 45, resources: [{ name: "Code",   url: "https://learnhub.com/r/vue-l2.zip"    }], isFree: false, createdAt: new Date("2024-03-20") },
  { courseId: redisCourse._id,   title: "Introduction à Redis",                content: "Types de données Redis et commandes de base.",            type: "video", order: 1, duration: 30, resources: [{ name: "Slides", url: "https://learnhub.com/r/redis-l1.pdf"   }], isFree: true,  createdAt: new Date("2024-08-01") },
  { courseId: redisCourse._id,   title: "Cache et Pub/Sub",                    content: "Stratégies de cache et messaging avec Redis.",            type: "quiz",  order: 2, duration: 40, resources: [{ name: "Exercices", url: "https://learnhub.com/r/redis-l2.pdf"}], isFree: false, createdAt: new Date("2024-08-01") },
  { courseId: awsCourse._id,     title: "Introduction à AWS",                  content: "IAM, régions et services fondamentaux.",                  type: "video", order: 1, duration: 40, resources: [{ name: "Slides", url: "https://learnhub.com/r/aws-l1.pdf"     }], isFree: true,  createdAt: new Date("2024-01-25") },
  { courseId: awsCourse._id,     title: "EC2, S3 et Lambda",                   content: "Déployer des instances, stocker des fichiers, fonctions.", type: "video", order: 2, duration: 60, resources: [{ name: "Code",   url: "https://learnhub.com/r/aws-l2.zip"    }], isFree: false, createdAt: new Date("2024-01-25") },
  { courseId: jsCourse._id,      title: "JavaScript Moderne — Les bases",      content: "let/const, arrow functions et template literals.",        type: "video", order: 1, duration: 30, resources: [{ name: "Slides", url: "https://learnhub.com/r/js-l1.pdf"      }], isFree: true,  createdAt: new Date("2024-04-10") },
  { courseId: jsCourse._id,      title: "Async/Await et Modules ES6",          content: "Promises, async/await et import/export.",                 type: "text",  order: 2, duration: 40, resources: [{ name: "Exercices", url: "https://learnhub.com/r/js-l2.pdf" }], isFree: false, createdAt: new Date("2024-04-10") },
  { courseId: nlpCourse._id,     title: "Introduction au NLP",                 content: "Tokenisation, stemming et représentations textuelles.",   type: "video", order: 1, duration: 45, resources: [{ name: "Slides", url: "https://learnhub.com/r/nlp-l1.pdf"    }], isFree: true,  createdAt: new Date("2024-02-28") },
  { courseId: nlpCourse._id,     title: "Transformers et Hugging Face",        content: "BERT, GPT et fine-tuning de modèles pré-entraînés.",      type: "video", order: 2, duration: 65, resources: [{ name: "Notebook", url: "https://learnhub.com/r/nlp-l2.ipynb"}], isFree: false, createdAt: new Date("2024-02-28") }
]);

print("✅ Lessons : " + db.lessons.countDocuments());

const lessonsMongo  = db.lessons.find({ courseId: mongoCourse._id  }).toArray();
const lessonsReact  = db.lessons.find({ courseId: reactCourse._id  }).toArray();
const lessonsDocker = db.lessons.find({ courseId: dockerCourse._id }).toArray();
const lessonsML     = db.lessons.find({ courseId: mlCourse._id     }).toArray();
const lessonsNode   = db.lessons.find({ courseId: nodeCourse._id   }).toArray();
const lessonsJS     = db.lessons.find({ courseId: jsCourse._id     }).toArray();
const lessonsDL     = db.lessons.find({ courseId: dlCourse._id     }).toArray();
const lessonsVue    = db.lessons.find({ courseId: vueCourse._id    }).toArray();

const alice    = db.users.findOne({ email: "alice.martin@email.com"     });
const clara    = db.users.findOne({ email: "clara.lefebvre@email.com"   });
const emma     = db.users.findOne({ email: "emma.bernard@email.com"     });
const felix    = db.users.findOne({ email: "felix.garnier@email.com"    });
const gaelle   = db.users.findOne({ email: "gaelle.petit@email.com"     });
const isabelle = db.users.findOne({ email: "isabelle.laurent@email.com" });
const julien   = db.users.findOne({ email: "julien.roux@email.com"      });
const karen    = db.users.findOne({ email: "karen.michel@email.com"     });
const marie    = db.users.findOne({ email: "marie.blanc@email.com"      });
const nicolas  = db.users.findOne({ email: "nicolas.renard@email.com"   });
const quentin  = db.users.findOne({ email: "quentin.leclerc@email.com"  });
const samuel   = db.users.findOne({ email: "samuel.vincent@email.com"   });
const tina     = db.users.findOne({ email: "tina.robert@email.com"      });

// ══════════════════════════════════════════════
// ENROLLMENTS — 25 documents
// ══════════════════════════════════════════════
db.enrollments.insertMany([
  { userId: alice._id,    courseId: mongoCourse._id,  status: "active",    progress: { completedLessons: [lessonsMongo[0]._id,  lessonsMongo[1]._id  ], percentage: 30,  lastAccessedAt: new Date("2024-12-01") }, payment: { amount: 49.99, method: "card",   paidAt: new Date("2024-06-15") }, enrolledAt: new Date("2024-06-15"), completedAt: null },
  { userId: alice._id,    courseId: reactCourse._id,  status: "completed", progress: { completedLessons: [lessonsReact[0]._id,  lessonsReact[1]._id  ], percentage: 100, lastAccessedAt: new Date("2024-11-20") }, payment: { amount: 89.99, method: "card",   paidAt: new Date("2024-07-01") }, enrolledAt: new Date("2024-07-01"), completedAt: new Date("2024-11-20") },
  { userId: alice._id,    courseId: nodeCourse._id,   status: "paused",    progress: { completedLessons: [lessonsNode[0]._id                          ], percentage: 50,  lastAccessedAt: new Date("2024-10-05") }, payment: { amount: 44.99, method: "paypal", paidAt: new Date("2024-08-10") }, enrolledAt: new Date("2024-08-10"), completedAt: null },
  { userId: clara._id,    courseId: jsCourse._id,     status: "active",    progress: { completedLessons: [lessonsJS[0]._id                            ], percentage: 20,  lastAccessedAt: new Date("2024-12-10") }, payment: { amount: 19.99, method: "card",   paidAt: new Date("2024-09-01") }, enrolledAt: new Date("2024-09-01"), completedAt: null },
  { userId: clara._id,    courseId: reactCourse._id,  status: "cancelled", progress: { completedLessons: [],                                           percentage: 0,   lastAccessedAt: new Date("2024-09-05") }, payment: { amount: 89.99, method: "card",   paidAt: new Date("2024-09-01") }, enrolledAt: new Date("2024-09-01"), completedAt: null },
  { userId: emma._id,     courseId: mlCourse._id,     status: "active",    progress: { completedLessons: [lessonsML[0]._id,    lessonsML[1]._id       ], percentage: 45,  lastAccessedAt: new Date("2024-11-15") }, payment: { amount: 79.99, method: "paypal", paidAt: new Date("2024-05-20") }, enrolledAt: new Date("2024-05-20"), completedAt: null },
  { userId: felix._id,    courseId: dockerCourse._id, status: "completed", progress: { completedLessons: [lessonsDocker[0]._id, lessonsDocker[1]._id  ], percentage: 100, lastAccessedAt: new Date("2024-10-30") }, payment: { amount: 69.99, method: "card",   paidAt: new Date("2024-04-10") }, enrolledAt: new Date("2024-04-10"), completedAt: new Date("2024-10-30") },
  { userId: felix._id,    courseId: cicdCourse._id,   status: "active",    progress: { completedLessons: [ObjectId(),           ObjectId()            ], percentage: 60,  lastAccessedAt: new Date("2024-12-08") }, payment: { amount: 29.99, method: "card",   paidAt: new Date("2024-10-01") }, enrolledAt: new Date("2024-10-01"), completedAt: null },
  { userId: felix._id,    courseId: mongoCourse._id,  status: "paused",    progress: { completedLessons: [lessonsMongo[0]._id                         ], percentage: 25,  lastAccessedAt: new Date("2024-09-20") }, payment: { amount: 49.99, method: "free",   paidAt: new Date("2024-06-01") }, enrolledAt: new Date("2024-06-01"), completedAt: null },
  { userId: felix._id,    courseId: dlCourse._id,     status: "cancelled", progress: { completedLessons: [],                                           percentage: 0,   lastAccessedAt: new Date("2024-07-01") }, payment: { amount: 99.99, method: "card",   paidAt: new Date("2024-07-01") }, enrolledAt: new Date("2024-07-01"), completedAt: null },
  { userId: gaelle._id,   courseId: jsCourse._id,     status: "completed", progress: { completedLessons: [lessonsJS[0]._id,    lessonsJS[1]._id       ], percentage: 100, lastAccessedAt: new Date("2024-11-01") }, payment: { amount: 19.99, method: "card",   paidAt: new Date("2024-08-15") }, enrolledAt: new Date("2024-08-15"), completedAt: new Date("2024-11-01") },
  { userId: gaelle._id,   courseId: vueCourse._id,    status: "active",    progress: { completedLessons: [lessonsVue[0]._id                           ], percentage: 35,  lastAccessedAt: new Date("2024-12-05") }, payment: { amount: 54.99, method: "paypal", paidAt: new Date("2024-11-01") }, enrolledAt: new Date("2024-11-01"), completedAt: null },
  { userId: isabelle._id, courseId: reactCourse._id,  status: "active",    progress: { completedLessons: [lessonsReact[0]._id,  lessonsReact[1]._id   ], percentage: 70,  lastAccessedAt: new Date("2024-12-02") }, payment: { amount: 89.99, method: "card",   paidAt: new Date("2024-09-10") }, enrolledAt: new Date("2024-09-10"), completedAt: null },
  { userId: isabelle._id, courseId: nodeCourse._id,   status: "completed", progress: { completedLessons: [lessonsNode[0]._id,   lessonsNode[1]._id    ], percentage: 100, lastAccessedAt: new Date("2024-11-28") }, payment: { amount: 44.99, method: "card",   paidAt: new Date("2024-07-20") }, enrolledAt: new Date("2024-07-20"), completedAt: new Date("2024-11-28") },
  { userId: isabelle._id, courseId: vueCourse._id,    status: "paused",    progress: { completedLessons: [lessonsVue[0]._id                           ], percentage: 15,  lastAccessedAt: new Date("2024-10-15") }, payment: { amount: 54.99, method: "free",   paidAt: new Date("2024-10-01") }, enrolledAt: new Date("2024-10-01"), completedAt: null },
  { userId: julien._id,   courseId: pgCourse._id,     status: "cancelled", progress: { completedLessons: [],                                           percentage: 0,   lastAccessedAt: new Date("2024-04-25") }, payment: { amount: 74.99, method: "card",   paidAt: new Date("2024-04-20") }, enrolledAt: new Date("2024-04-20"), completedAt: null },
  { userId: karen._id,    courseId: mlCourse._id,     status: "completed", progress: { completedLessons: [lessonsML[0]._id,    lessonsML[1]._id       ], percentage: 100, lastAccessedAt: new Date("2024-11-30") }, payment: { amount: 79.99, method: "card",   paidAt: new Date("2024-03-15") }, enrolledAt: new Date("2024-03-15"), completedAt: new Date("2024-11-30") },
  { userId: karen._id,    courseId: dlCourse._id,     status: "active",    progress: { completedLessons: [lessonsDL[0]._id,    lessonsDL[1]._id       ], percentage: 55,  lastAccessedAt: new Date("2024-12-09") }, payment: { amount: 99.99, method: "paypal", paidAt: new Date("2024-08-01") }, enrolledAt: new Date("2024-08-01"), completedAt: null },
  { userId: marie._id,    courseId: mongoCourse._id,  status: "active",    progress: { completedLessons: [lessonsMongo[0]._id,  lessonsMongo[1]._id   ], percentage: 80,  lastAccessedAt: new Date("2024-11-25") }, payment: { amount: 49.99, method: "card",   paidAt: new Date("2024-07-10") }, enrolledAt: new Date("2024-07-10"), completedAt: null },
  { userId: marie._id,    courseId: vueCourse._id,    status: "completed", progress: { completedLessons: [lessonsVue[0]._id,   lessonsVue[1]._id     ], percentage: 100, lastAccessedAt: new Date("2024-11-10") }, payment: { amount: 54.99, method: "card",   paidAt: new Date("2024-08-20") }, enrolledAt: new Date("2024-08-20"), completedAt: new Date("2024-11-10") },
  { userId: nicolas._id,  courseId: jsCourse._id,     status: "active",    progress: { completedLessons: [lessonsJS[0]._id                            ], percentage: 40,  lastAccessedAt: new Date("2024-12-11") }, payment: { amount: 19.99, method: "free",   paidAt: new Date("2024-10-05") }, enrolledAt: new Date("2024-10-05"), completedAt: null },
  { userId: quentin._id,  courseId: mongoCourse._id,  status: "completed", progress: { completedLessons: [lessonsMongo[0]._id,  lessonsMongo[1]._id   ], percentage: 100, lastAccessedAt: new Date("2024-10-20") }, payment: { amount: 49.99, method: "card",   paidAt: new Date("2024-04-01") }, enrolledAt: new Date("2024-04-01"), completedAt: new Date("2024-10-20") },
  { userId: samuel._id,   courseId: reactCourse._id,  status: "active",    progress: { completedLessons: [lessonsReact[0]._id,  lessonsReact[1]._id   ], percentage: 65,  lastAccessedAt: new Date("2024-12-06") }, payment: { amount: 89.99, method: "card",   paidAt: new Date("2024-06-20") }, enrolledAt: new Date("2024-06-20"), completedAt: null },
  { userId: samuel._id,   courseId: nodeCourse._id,   status: "paused",    progress: { completedLessons: [lessonsNode[0]._id                          ], percentage: 10,  lastAccessedAt: new Date("2024-11-01") }, payment: { amount: 44.99, method: "paypal", paidAt: new Date("2024-09-15") }, enrolledAt: new Date("2024-09-15"), completedAt: null },
  { userId: tina._id,     courseId: jsCourse._id,     status: "active",    progress: { completedLessons: [lessonsJS[0]._id,    lessonsJS[1]._id       ], percentage: 90,  lastAccessedAt: new Date("2024-10-28") }, payment: { amount: 19.99, method: "card",   paidAt: new Date("2024-07-15") }, enrolledAt: new Date("2024-07-15"), completedAt: null }
]);

print("✅ Enrollments : " + db.enrollments.countDocuments());

// ══════════════════════════════════════════════
// REVIEWS — 20 documents
// ══════════════════════════════════════════════
db.reviews.insertMany([
  { userId: alice._id,    courseId: reactCourse._id,  rating: 5, title: "Excellent cours !",          comment: "Très bien expliqué, les hooks avancés sont enfin clairs.",       isVerified: true,  helpfulCount: 14, createdAt: new Date("2024-11-25"), updatedAt: null },
  { userId: felix._id,    courseId: dockerCourse._id, rating: 5, title: "Parfait pour débuter",       comment: "Kubernetes bien expliqué, exemples concrets et pratiques.",       isVerified: true,  helpfulCount: 9,  createdAt: new Date("2024-11-05"), updatedAt: null },
  { userId: gaelle._id,   courseId: jsCourse._id,     rating: 4, title: "Très bon contenu",           comment: "ES2024 bien couvert, quelques exercices supplémentaires seraient bienvenus.", isVerified: true,  helpfulCount: 6,  createdAt: new Date("2024-11-10"), updatedAt: null },
  { userId: isabelle._id, courseId: nodeCourse._id,   rating: 5, title: "Je recommande vivement",     comment: "Cours complet, la partie JWT est très bien détaillée.",           isVerified: true,  helpfulCount: 11, createdAt: new Date("2024-12-01"), updatedAt: null },
  { userId: karen._id,    courseId: mlCourse._id,     rating: 5, title: "Formation de qualité",       comment: "Scikit-learn expliqué avec des cas réels, excellent !",           isVerified: true,  helpfulCount: 18, createdAt: new Date("2024-12-02"), updatedAt: null },
  { userId: marie._id,    courseId: vueCourse._id,    rating: 4, title: "Bon cours sur Vue.js 3",     comment: "Pinia bien expliqué, j'attendais ce contenu depuis longtemps.",   isVerified: true,  helpfulCount: 7,  createdAt: new Date("2024-11-15"), updatedAt: null },
  { userId: quentin._id,  courseId: mongoCourse._id,  rating: 5, title: "Meilleur cours MongoDB",     comment: "Agrégations très bien détaillées, je recommande à tous.",         isVerified: true,  helpfulCount: 21, createdAt: new Date("2024-10-25"), updatedAt: null },
  { userId: alice._id,    courseId: mongoCourse._id,  rating: 4, title: "Contenu solide",             comment: "Bonne introduction, j'aurais voulu plus d'exemples avancés.",     isVerified: false, helpfulCount: 3,  createdAt: new Date("2024-12-03"), updatedAt: null },
  { userId: emma._id,     courseId: mlCourse._id,     rating: 4, title: "Très pédagogique",           comment: "Les notebooks Jupyter sont bien structurés et clairs.",           isVerified: false, helpfulCount: 5,  createdAt: new Date("2024-11-20"), updatedAt: null },
  { userId: felix._id,    courseId: cicdCourse._id,   rating: 4, title: "Pratique et efficace",       comment: "Pipeline CI/CD opérationnel dès la fin du cours.",                isVerified: false, helpfulCount: 8,  createdAt: new Date("2024-12-09"), updatedAt: null },
  { userId: clara._id,    courseId: jsCourse._id,     rating: 3, title: "Correct mais incomplet",     comment: "Manque quelques sujets modernes comme les Web Workers.",          isVerified: false, helpfulCount: 2,  createdAt: new Date("2024-12-11"), updatedAt: null },
  { userId: samuel._id,   courseId: reactCourse._id,  rating: 5, title: "Vraiment impressionnant",    comment: "Le meilleur cours React que j'ai suivi, très complet.",           isVerified: false, helpfulCount: 15, createdAt: new Date("2024-12-07"), updatedAt: null },
  { userId: karen._id,    courseId: dlCourse._id,     rating: 5, title: "Deep Learning enfin clair",  comment: "PyTorch expliqué progressivement, CNN très bien illustré.",        isVerified: false, helpfulCount: 12, createdAt: new Date("2024-12-10"), updatedAt: null },
  { userId: marie._id,    courseId: mongoCourse._id,  rating: 4, title: "Bon pour les débutants",     comment: "Explications claires, parfait pour démarrer avec MongoDB.",       isVerified: false, helpfulCount: 4,  createdAt: new Date("2024-11-28"), updatedAt: null },
  { userId: nicolas._id,  courseId: jsCourse._id,     rating: 4, title: "Bien structuré",             comment: "Async/await enfin bien compris grâce aux exemples du cours.",     isVerified: false, helpfulCount: 6,  createdAt: new Date("2024-12-12"), updatedAt: null },
  { userId: tina._id,     courseId: jsCourse._id,     rating: 3, title: "Moyen sur la fin",           comment: "Bon début mais les dernières leçons manquent d'exercices.",       isVerified: false, helpfulCount: 1,  createdAt: new Date("2024-10-30"), updatedAt: null },
  { userId: gaelle._id,   courseId: vueCourse._id,    rating: 5, title: "Très bon formateur",         comment: "Pierre explique clairement, les projets pratiques sont top.",     isVerified: false, helpfulCount: 9,  createdAt: new Date("2024-12-06"), updatedAt: null },
  { userId: isabelle._id, courseId: reactCourse._id,  rating: 4, title: "Hooks bien expliqués",       comment: "useCallback et useMemo enfin maîtrisés grâce à ce cours.",        isVerified: false, helpfulCount: 7,  createdAt: new Date("2024-12-03"), updatedAt: null },
  { userId: quentin._id,  courseId: redisCourse._id,  rating: 4, title: "Redis accessible",           comment: "Pub/Sub et cache bien expliqués avec des cas concrets.",          isVerified: false, helpfulCount: 5,  createdAt: new Date("2024-11-18"), updatedAt: null },
  { userId: samuel._id,   courseId: nodeCourse._id,   rating: 4, title: "Solide pour le backend",     comment: "Express bien structuré, la gestion des erreurs est très claire.",  isVerified: false, helpfulCount: 8,  createdAt: new Date("2024-12-08"), updatedAt: null }
]);

print("✅ Reviews : " + db.reviews.countDocuments());
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
print("✅ Seed terminé !");
print("   Users       : " + db.users.countDocuments());
print("   Courses      : " + db.courses.countDocuments());
print("   Lessons      : " + db.lessons.countDocuments());
print("   Enrollments  : " + db.enrollments.countDocuments());
print("   Reviews      : " + db.reviews.countDocuments());
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
